# Generated by Django 3.0.4 on 2020-05-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustticketmodel',
            name='user',
        ),
    ]
