# Generated by Django 3.0.4 on 2020-05-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0005_signinstudentmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SigninStudentModel',
            new_name='SigninModel',
        ),
    ]
